### ISSUE TITLE
How to train FC-CLIP on a semantic segmentation dataset?

### ISSUE THREAD

**Issue by lartpang** [bytedance/fc-clip#7]
The code ran into such errors when using my own semantic segmentation dataset, but everything seemed to work fine when tested directly with the weights you provided. Why is that?

@cornettoyu 

---

In `configs`:

```yaml
_BASE_: ./fcclip_convnext_large_eval_ade20k.yaml
MODEL:
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (40000, 55000)
  MAX_ITER: 60000

DATASETS:
  TRAIN: ("openvocab_train_sem_seg",)
  TEST: ("openvocab_test_sem_seg",)
```

In fcclip/data/datasets:

```python
def register_ovseg(root):
    root = os.path.join(root, "mydata", MyDataset)

    color_mapping = colors.LinearSegmentedColormap.from_list(
        "mycmap", ["red", "yellow", "green"]
    )

    for name, image_dirname, sem_seg_dirname, class_names in [
        ("train", "image", "detectron2", TRAIN_CLASS_NAMES),
        ("test", "image", "detectron2", TEST_CLASS_NAMES),
    ]:
        image_dir = os.path.join(root, name, image_dirname)
        gt_dir = os.path.join(root, name, sem_seg_dirname)

        dataset_name = f"openvocab_{name}_sem_seg"
        DatasetCatalog.register(
            dataset_name,
            lambda x=image_dir, y=gt_dir: load_sem_seg(
                y, x, gt_ext="png", image_ext="jpg"
            ),
        )

        class_colors = [[0, 0, 0]]
        for cls_idx in range(len(class_names)):
            color = [
                int(c)
                for c in color_mapping((cls_idx + 1) / len(class_names))[:3] * 255
            ]
            class_colors.append(color)

        # Id 0 is reserved for ignore_label, we change ignore_label for 0
        # to 255 in our pre-processing.
        stuff_ids = [k for k, c in enumerate(class_names)]  # start from 0

        # For semantic segmentation, this mapping maps from contiguous stuff id
        # (in [0, 91], used in models) to ids in the dataset (used for processing results)
        stuff_dataset_id_to_contiguous_id = {k: i for i, k in enumerate(stuff_ids)}
        MetadataCatalog.get(dataset_name).set(
            image_root=image_dir,
            sem_seg_root=gt_dir,
            evaluator_type="sem_seg",
            ignore_label=255,
            gt_ext="png",
            stuff_dataset_id_to_contiguous_id=stuff_dataset_id_to_contiguous_id,
            stuff_classes=class_names,
            stuff_colors=class_colors,
        )


_root = os.getenv("DETECTRON2_DATASETS", "datasets")
register_ovseg(_root)
```

Error:

```shell
ERROR [10/15 17:30:44 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 155, in train
    self.run_step()
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/detectron2/engine/defaults.py", line 496, in run_step
    self._trainer.run_step()
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/detectron2/engine/train_loop.py", line 494, in run_step
    loss_dict = self.model(data)
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/fcclip/fcclip/fcclip.py", line 340, in forward
    losses = self.criterion(outputs, targets)
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/fcclip/fcclip/modeling/criterion.py", line 226, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/fcclip/fcclip/modeling/matcher.py", line 183, in forward
    return self.memory_efficient_forward(outputs, targets)
  File "/root/miniconda3/envs/pt201/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/fcclip/fcclip/modeling/matcher.py", line 110, in memory_efficient_forward
    tgt_ids = targets[b]["labels"]
TypeError: 'NoneType' object is not subscriptable
[10/15 17:30:44 d2.engine.hooks]: Total training time: 0:00:04 (0:00:00 on hooks)
```

**Comment by cornettoyu** [comment]
Hi, I think you may need to modify the dataloader as well to make it work with your dataset, you may take Mask2Former's [dataloader](https://github.com/facebookresearch/Mask2Former/blob/main/mask2former/data/dataset_mappers/mask_former_semantic_dataset_mapper.py) for semantic dataset as a reference.

**Comment by lartpang** [comment]
@cornettoyu 
Thanks for your reply.
Referring to the code you provide, I have implemented a semantic segmentation code by myself, which has been successfully executed.

**Comment by Irennnne** [comment]
I think this can be fixed by adding 
`INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic"`
in the config file

**Comment by Kimsure** [comment]
It works. We can use `mask_former_semantic` mapper and `register_coco_stuff_164k` register for training on coco-stuff dataset.
